# Generated by Django 4.1.5 on 2023-01-19 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название продукта')),
                ('model', models.CharField(max_length=100, verbose_name='Модель продукта')),
                ('release_date', models.DateField(verbose_name='Дата выхода на рынок')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hierarchy', models.SmallIntegerField(choices=[(0, 'Завод'), (1, 'Дистрибьютер'), (2, 'Диллерский центр'), (3, 'Крупная розничная сеть'), (4, 'Индивидуальный предприниматель')], verbose_name='Тип компании')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тип компании')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('country', models.CharField(max_length=25, verbose_name='Название страны')),
                ('city', models.CharField(max_length=25, verbose_name='Название города')),
                ('street', models.CharField(max_length=50, verbose_name='Название улицы')),
                ('building', models.CharField(max_length=25, verbose_name='Номер дома и офис')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Задолженность')),
                ('pub_data', models.DateField(auto_now_add=True)),
                ('products', models.ManyToManyField(related_name='companies', to='companies.product')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traders', to='companies.company', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
    ]
